# This should match the minimum supported Pixi version
#:schema https://pixi.prefix.dev/v0.71.0/schema/manifest/schema.json

[workspace]
name = "kimnara-playground"
channels = ["conda-forge"]
platforms = [
    "linux-64",
    { platform = "osx-64", macos = "10.15" },
    "win-64",
]
preview = ["pixi-build"]
requires-pixi = ">=0.71.0"

[workspace.build-variants]
microarch_level = ["1"]

[workspace.target.linux-64.build-variants]
c_compiler = ["gcc"]
c_compiler_version = ["16.2"]
cxx_compiler = ["gxx"]
cxx_compiler_version = ["16.2"]

[workspace.target.osx-64.build-variants]
c_compiler = ["clang"]
c_compiler_version = ["21.1"]
cxx_compiler = ["clangxx"]
cxx_compiler_version = ["21.1"]

[workspace.target.win-64.build-variants]
c_compiler = ["vs"]
c_compiler_version = ["2026.1"]
c_stdlib = ["vs"]
c_stdlib_version = ["2026.1"]
cxx_compiler = ["vs"]
cxx_compiler_version = ["2026.1"]

[environments]
default = ["builder"]
node = ["node"]
clang = ["clang"]
gcc = ["gcc"]
intel = ["intel"]
msvc = ["msvc"]
nb057 = ["kimnara-py311", "numba", "nb057", "pyomp"]
nb058 = ["kimnara-py311", "numba", "nb058", "pyomp", "svml"]
nb059 = ["kimnara", "numba", "nb059", "pyomp", "svml"]
nb060 = ["kimnara", "numba", "nb060", "pyomp", "svml"]
nb061 = ["kimnara", "numba", "nb061", "pyomp"]
nb062 = ["kimnara", "numba", "nb062", "pyomp"]
nb063 = ["kimnara", "numba", "nb063", "pyomp"]
nb064 = ["kimnara", "numba", "nb064"]
nb065 = ["kimnara", "numba", "nb065"]
nb066 = ["kimnara", "numba", "nb066"]
nb067 = ["kimnara", "numba", "nb067"]
nb068 = ["kimnara", "numba", "nb068"]
conda = ["conda"]

[feature.conda.dependencies]
conda = ">=25.9.0"
conda-build = "*"

[feature.kimnara.dependencies.kimnara]
git = "https://github.com/hingebase/kimnara"
branch = "main"
subdirectory = "packages/kimnara"

[feature.kimnara.target]
linux-64.dependencies.cuda-bindings = "12.*"
win-64.dependencies.cuda-bindings = "12.*"

[feature.kimnara-py311.dependencies.kimnara]
git = "https://github.com/hingebase/kimnara"
branch = "main"
subdirectory = "packages/kimnara-py311"

[feature.kimnara-py311.target]
linux-64.dependencies.cuda-bindings = "12.*"
win-64.dependencies.cuda-bindings = "11.*"

[feature.builder]
channels = ["conda-forge", "https://prefix.dev/github-releases"]

[feature.builder.dependencies]
kimnara-playground-builder = { path = "packages/kimnara-playground-builder" }

[feature.builder.target]
linux-64.dependencies.pixi = ">=0.76.0"
osx-64.dependencies.pixi = { version = "0.71.*", channel = "https://prefix.dev/github-releases" }

[feature.builder.target.win-64.dependencies]
m2-coreutils = "*"
m2-findutils = "*"
m2-sed = "*"
m2-which = "*"
pixi = ">=0.76.0"

[feature.builder.tasks._prepare]
cmd = 'pixi i -a --locked && test -f dist.zip && exit 0; echo "$MESSAGE"; exit 1'

[feature.builder.tasks._prepare.env]
GITHUB_ACTIONS = "https://github.com/compiler-explorer/compiler-explorer/actions/workflows/test-and-deploy.yml"
MESSAGE = "Please grab a recent 'dist.zip' from $GITHUB_ACTIONS and place it at '$PIXI_PROJECT_ROOT'."

[feature.builder.tasks._setup]
cmd = "rm -rf compiler-explorer && python -m kimnara_playground_builder"
depends-on = ["_prepare"]
inputs = ["dist.zip", "pixi.lock"]
outputs = [
    "compiler-explorer/discovered-compilers.json",
    "compiler-explorer/etc/config/c.local.properties",
    "compiler-explorer/etc/config/c++.local.properties",
    "compiler-explorer/etc/config/numba.local.properties",
    "compiler-explorer/etc/config/versionFlag.txt",
    "compiler-explorer/release_build",
]

[feature.node.tasks.start]
cmd = "node app.js --prediscovered discovered-compilers.json"
cwd = "compiler-explorer"
depends-on = ["_setup"]
env = { NODE_ENV = "production" }

[feature.node.target]
linux-64.dependencies.nodejs = "26.*"
osx-64.dependencies.nodejs = "24.*"
win-64.dependencies.nodejs = "26.*"

## C/C++ compilers

[feature.clang.target.linux-64.dependencies]
clangxx_linux-64 = ">=19.1.0"
llvm-tools = ">=19.1.0"

[feature.clang.target.osx-64.dependencies]
clangxx_osx-64 = ">=19.1.0"

[feature.clang.target.win-64.dependencies]
clangxx = ">=19.1.0"
llvm-tools = "*"
vs_win-64 = ">=2026.1.0"

[feature.gcc.target]
linux-64.dependencies.gxx_linux-64 = ">=14.1.0"
osx-64.dependencies.gxx_osx-64 = ">=14.1.0"
win-64.dependencies.gxx_win-64 = ">=14.1.0"

[feature.intel]
platforms = ["linux-64", "win-64"]

[feature.intel.dependencies]
onedpl-devel = "*"

[feature.intel.target.linux-64.dependencies]
dpcpp_linux-64 = ">=2025.0.0"

[feature.intel.target.win-64.dependencies]
dpcpp_win-64 = ">=2025.0.0"
vs_win-64 = ">=2026.1.0"

[feature.msvc]
platforms = ["win-64"]

[feature.msvc.dependencies]
vs_win-64 = ">=2026.1.0"

## Numba

[feature]
nb058.dependencies.numba = "==0.58.1"
nb059.dependencies.numba = "==0.59.1"
nb060.dependencies.numba = "==0.60.0"
nb061.dependencies.numba = "==0.61.2"
nb062.dependencies.numba = "==0.62.1"
nb063 = { dependencies.numba = "==0.63.1", platforms = ["linux-64", "win-64"] }
nb064 = { dependencies.numba = "==0.64.0", platforms = ["linux-64", "win-64"] }
nb065 = { dependencies.numba = "==0.65.1", platforms = ["linux-64", "win-64"] }
nb066 = { dependencies.numba = "==0.66.0", platforms = ["linux-64", "win-64"] }
nb067 = { dependencies.numba = "==0.67.0", platforms = ["linux-64", "win-64"] }
nb068 = { dependencies.numba = "0.68.*", platforms = ["linux-64", "win-64"] }

[feature.nb057]
channels = ["conda-forge", "numba", "https://software.repos.intel.com/python/conda"]

[feature.nb057.target.linux-64.dependencies]
numba = { version = "==0.57.1", channel = "conda-forge" }

[feature.nb057.target.osx-64.dependencies]
icc_rt = { channel = "numba" }
llvmlite = { channel = "numba" }
numba = { version = "==0.57.1", channel = "numba" }

[feature.nb057.target.win-64.dependencies]
intel-cmplr-lib-rt = { channel = "conda-forge" }
llvmlite = { channel = "numba" }
numba = { version = "==0.57.1", channel = "numba" }
tbb = { channel = "https://software.repos.intel.com/python/conda" }

[feature.numba.dependencies]
kimnara-playground-runner = { path = "packages/kimnara-playground-runner" }
libblas = { build = "*_mkl" }
psutil = "*"

[feature.pyomp]
channels = ["Python-for-HPC"]
target.linux-64.dependencies.pyomp = { version = ">=0.3.2", channel = "Python-for-HPC" }

[feature.svml]
channels = ["conda-forge", "numba"]
target.linux-64.dependencies.intel-cmplr-lib-rt.channel = "conda-forge"
target.osx-64.dependencies.icc_rt.channel = "numba"
target.win-64.dependencies.intel-cmplr-lib-rt.channel = "conda-forge"
